apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: contrailmanagers.contrail.juniper.net
spec:
  additionalPrinterColumns:
  - JSONPath: .status.active
    description: Defines whether contrail is active
    name: Active
    type: string
  - JSONPath: .status.completed
    description: The status if contrail has completed
    name: Completed
    type: string
  - JSONPath: .status.platform.orchestrator
    description: The platform
    name: Platform
    type: string
  - JSONPath: .status.cassandraStatus
    description: The status of cassandra
    name: cassandraStatus
    type: boolean
  group: contrail.juniper.net
  names:
    kind: ContrailManager
    listKind: ContrailManagerList
    plural: contrailmanagers
    singular: contrailmanager
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            components:
              items:
                properties:
                  crd:
                    type: string
                  name:
                    type: string
                type: object
              type: array
            configMaps:
              items:
                properties:
                  envs:
                    additionalProperties:
                      type: string
                    type: object
                  name:
                    type: string
                type: object
              type: array
            globalConfig:
              properties:
                hostNetwork:
                  type: boolean
                imagePullSecrets:
                  items:
                    type: string
                  type: array
                nodeSelector:
                  additionalProperties:
                    type: string
                  type: object
                platform:
                  properties:
                    orchestrator:
                      type: string
                  type: object
                registry:
                  properties:
                    name:
                      type: string
                    password:
                      type: string
                    tag:
                      type: string
                    user:
                      type: string
                  type: object
                replicas:
                  format: int32
                  type: integer
                serviceAccount:
                  type: string
              type: object
            nodeConfig:
              properties:
                components:
                  items:
                    type: string
                  type: array
                configMaps:
                  items:
                    properties:
                      envs:
                        additionalProperties:
                          type: string
                        type: object
                      name:
                        type: string
                    type: object
                  type: array
                hostname:
                  type: string
                nodeIp:
                  type: string
              type: object
          type: object
        status:
          properties:
            active:
              type: boolean
            cassandraStatus:
              type: boolean
            completed:
              type: boolean
            platform:
              properties:
                orchestrator:
                  type: string
              type: object
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
