apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: contrailmanagers.contrail.juniper.net
spec:
  group: contrail.juniper.net
  names:
    kind: ContrailManager
    listKind: ContrailManagerList
    plural: contrailmanagers
    singular: contrailmanager
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          type: object
        status:
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
