apiVersion: contrail.juniper.net/v1alpha1
kind: ContrailManager
metadata:
  name: cluster-1
spec:
  globalConfig:
    registry:
      name: "opencontrailnightly"
      tag: "latest"
#     user:
#     password:
    imagePullSecrets:
      - "registry-secrets"
    serviceAccount: "contrail-manager-operator-sa"
    nodeSelector: {
        "node-role.kubernetes.io/master": ""
    }
    replicas: 1
    hostNetwork: true
    platform:
      orchestrator: "kubernetes"
  nodeConfig:
    - nodeIp: "10.1.1.1"
      hostname: "node1"
      components:
        - "configdb"
      configmaps:
        - name: "node1-cm"
          envs: {
            VROUTER_GATEWAY: "10.1.1.1",
          }
    - nodeIp: "20.1.1.1"
      hostname: "node2"
      components:
        - "*"
      configmaps:
        - name: "node2-cm"
          envs: {
            VROUTER_GATEWAY: "10.1.1.1",
          }
  configMaps:
    - name: "common-env"
      envs: {
        ORCHESTRATOR: "kubernetes"
      }
    - name: "cassandra-node-init-env"
      envs: {
        NODE_TYPE: "config-database"
      }
  components:
    - name: "configdb"
      crd:  "ContrailCassandra"
      configuration:
        containers:
          - name: "node-init"
            image: "opencontrailnightly/contrail-node-init:latest"
            configMaps:
              - "common-env"
              - "cassandra-node-init-env"
          - name: "cassandra"
            image: "opencontrailnightly/contrail-external-cassandra:latest"
            configMaps:
              - "common-env"
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
