apiVersion: apps/v1
kind: Deployment
metadata:
  name: contrail-manager-test-1
spec:
  replicas: 1
  selector:
    matchLabels:
      name: contrail-manager-test-1
  template:
    metadata:
      labels:
        name: contrail-manager-test-1
    spec:
      serviceAccountName: contrail-manager-test-1
      containers:
        - name: contrail-manager-test-1
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - contrail-manager-test-1
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "contrail-manager-test-1"
