kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: contrail-manager-test-2
subjects:
- kind: ServiceAccount
  name: contrail-manager-test-2
roleRef:
  kind: Role
  name: contrail-manager-test-2
  apiGroup: rbac.authorization.k8s.io
